# Generated by Django 4.2.7 on 2023-12-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.test', verbose_name='тест'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён'),
        ),
    ]
