# Generated by Django 4.2.7 on 2024-01-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_choice_question_question_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('T', 'текстовый ответ'), ('C', 'варианты ответов')], max_length=2, verbose_name='тип вопроса'),
        ),
    ]
